version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - cd SimpleApplication
      - mvn clean package -DskipTests
      - cp target/*.jar app.jar

artifacts:
  base-directory: SimpleApplication
  files:
    - app.jar
    - Procfile
  discard-paths: yes
