version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - cd SimpleApplication
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests

artifacts:
  files:
    - SimpleApplication/target/*.jar
    - SimpleApplication/Procfile
