version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - echo Pre-build phase
      - cd demo
      - mvn clean

  build:
    commands:
      - echo Build started
      - mvn package -DskipTests

artifacts:
  files:
    - demo/target/*.jar
  discard-paths: yes
