version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - cd SimpleApplication
      - mvn -DskipTests clean package
      - mkdir -p deploy
      - cp target/*.jar deploy/app.jar
      - cp Procfile deploy/Procfile
      - cd deploy
      - zip -r ../deploy.zip .
artifacts:
  files:
    - SimpleApplication/deploy.zip
