version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install dependencies"
      - npm ci || npm install

  build:
    commands:
      - echo "Build step (optional) - nothing to compile for basic Node API"
      # If you have TypeScript / build step, uncomment:
      # - npm run build

artifacts:
  files:
    - "**/*"
  exclude-paths:
    - node_modules/**/*
    - .git/**/*
    - .github/**/*
